stages:
  - build_develop
  - build_production

before_script:
  - chmod +x ./gradlew
  - source ~/.zshrc

assembleDevDebug:
  tags:
    - autobuild
  only:
    refs:
      - develop
  stage: build_develop
  script:
    - ./gradlew clean
    - ./gradlew assembleDevDebug
    - curl -T $PWD/app/build/outputs/apk/dev/debug/app-dev-debug.apk -u $FTP_USER:$FTP_PASSWORD $FTP_FOLDER/social/icheckDev.apk
    - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Có bản cài Social Android Sandbox mới. <https://download.icheck.com.vn/|Tải ngay!>\"}' $SLACK_HOOK"

assembleProdRelease:
  tags:
    - autobuild
  only:
    refs:
      - develop
  stage: build_production
  script:
    - ./gradlew clean
    - ./gradlew assembleProdRelease
    - curl -T $PWD/app/build/outputs/apk/prod/release/app-prod-release.apk -u $FTP_USER:$FTP_PASSWORD $FTP_FOLDER/social/icheck.apk
    - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Có bản cài Social Android Live mới. <https://download.icheck.com.vn/|Tải ngay!>\"}' $SLACK_HOOK"