before_script:
  - chmod +x ./gradlew
  - source ~/.zshrc 

assembleProdRelease:
  tags:
    - autobuild
  only:
    refs:
      - master
  stage: build
  script:
    - ./gradlew clean
    - ./gradlew assembleProdRelease
    - curl -T $PWD/app/build/outputs/apk/prod/release/app-prod-release.apk -u $FTP_USER:$FTP_PASSWORD $FTP_FOLDER/social/icheck.apk
    - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Có bản cài Android Social Live mới. <https://download.icheck.com.vn/|Tải ngay!>\"}' $SLACK_HOOK"